<footer class="container-fluid text-center mt-3 text-light bg-primary">
  <div class="row align-items-center">
    <div class="col-lg">
      <p>ООО "Планета путешествий и развлечений"</p>
      <p><a class="text-light" href="/contacts">Контакты</a></p>
    </div>
    <div class="col-lg">
      <p>ИНН</p>
      <p>3123084912</p>
    </div>
    <div class="col-lg">
      <p>ОГРН</p>
      <p>1023101647360</p>
    </div>
    <div class="col-lg">
      <p>Номер в Общероссийском генеральном реестре туристических агентств</p>
      <p>BH100443</p>
    </div>
  </div>
</footer>
