<header class="container-fluid text-center bg-primary mb-3">
    <nav class="navbar navbar-expand-lg">
      <a class="navbar-brand" href="/">
        <?php
          use Phalcon\Tag;
          echo Tag::image(
            [
              'img/logo.webp',
              'alt' => 'Logo',
              'width' => '50',
              'height' => '50'
            ]
          );
         ?>
         <span class='text-uppercase font-weight-bold text-light' id='brand'>Планета путешествий и развлечений</span>
      </a>
      <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav m-auto">
          <li class="nav-item">
            <a class="nav-link text-light" href="/">Главная</a>
          </li>
          <li class="nav-item">
           <a class="nav-link text-light" href="/#aboutus" id='aboutLink'>О нас</a>
          </li>
          <li class="nav-item">
           <a class="nav-link text-light" href="/news">Новости</a>
          </li>
           <li class="nav-item">
           <a class="nav-link text-light" href="/tours">Туры</a>
          </li>
         <li class="nav-item">
           <a class="nav-link text-light" href="/transport">Пассажирские перевозки</a>
          </li>
          <li class="nav-item">
           <a class="nav-link text-light" href="/contacts">Контакты</a>
          </li>
        </ul>
      </div>
    </nav>
</header>
