<?php
    use Phalcon\Forms\Form;
    use Phalcon\Forms\Element\Email;
    use Phalcon\Forms\Element\Text;
    use Phalcon\Forms\Element\TextArea;
    $form = new Form();
    $form->add(
    new Email('contactFormEmail')
    );
    $form->add(
    new Text('contactFormName')
    );
    $form->add(
    new TextArea('contactFormQuestion')
  );
 ?>

<h1 class='text-uppercase text-light font-weight-bold text-center'>Контакты</h1>
<div class="container mt-3 text-light">
  <div class="row text-center d-flex align-items-center">
    <div class="col-lg">
      <img src="/img/phone.webp" alt="Телефон турагентства" class='contactLogo mb-2'>
      <p class='contactText'>+7 (920) 573-93-81</p>
      <p class='contactText'>+7 (920) 561-46-86</p>
      <img src="/img/email.webp" alt="Электронная почта турагентства" class='contactLogo mb-2'>
      <p class='contactText'>planetapr@mail.ru</p>
      <a rel='nofollow' target='_blank' href='https://vk.com/planeta_travel_bgd' class='socials'><img src="/img/vk.webp" alt="Vkontakte" class='contactLogo mb-2'></a>
      <a rel='nofollow' target='_blank' href='https://www.instagram.com/planeta.travel.bgd/' class='socials'><img src="/img/instagram.webp" alt="Instagram" class='contactLogo mb-2'></a>
    </div>
    <div class="col-lg">
      <p class='contactText'>г. Белгород ул. Гостёнская 14 офис 7</p>
      <p class='contactText'>Авиа- и ж/д кассы: Пн-Пт 10.00 - 18.00</p>
      <p class='contactText'>Турагентство: Пн-Пт 10.00 - 18.00</p>
      <p class='contactText'>Перерыв: 13.30 - 14.00</p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg">
      <iframe class='w-100' id='mapHeight' src="https://www.openstreetmap.org/export/embed.html?bbox=36.570535898208625%2C50.59517033069944%2C36.57819628715516%2C50.599855802965294&amp;layer=mapnik&amp;marker=50.59751312513607%2C36.574366092681885" style="border: 1px solid black"></iframe><br/><small><a rel='nofollow' href="https://www.openstreetmap.org/?mlat=50.59751&amp;mlon=36.57437#map=17/50.59751/36.57437" class='text-dark'>Посмотреть подробнее</a></small>
    </div>
    <div class="col-lg text-center mb-3">
      <video autoplay muted loop id='travelAgencyEntrance'>
       <source src="/video/travel-agency-entrance.mp4">
      </video>
    </div>
    <div class="col-lg">
      <div id="contactCarausel" class="carousel slide" data-ride="carousel align-self-center">
        <ol class="carousel-indicators">
          <li data-target="#contactCarauselTravelAgencyEntrance" data-slide-to="0" class="active"></li>
          <li data-target="#contactCarauselTravelAgencyReception" data-slide-to="1"></li>
          <li data-target="#contactCarauselTravelAgencyWorkSchedule" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div id='contactCarauselTravelAgencyEntrance' class="photoContactCarausel carousel-item active"></div>
          <div id='contactCarauselTravelAgencyReception' class="photoContactCarausel carousel-item"></div>
          <div id='contactCarauselTravelAgencyWorkSchedule' class="photoContactCarausel carousel-item"></div>
        </div>
        <a class="carousel-control-prev" href="#contactCarausel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#contactCarausel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
  <div class="row" id='supporForm'>
    <div class="col-lg">
        <h2 class='text-uppercase font-weight-bold mt-3 text-center' >Напишите нам</h2>
        <h3 class='text-uppercase font-weight-bold font-italic mt-3 text-center' >Ответим в ближайшее время</h3>
        <div id='contactFormMessage' class="alert text-center" role="alert"></div>
        <form id='contactForm' action="/ask" method='post'>
            <div class="form-group ">
                <p>
                    <label for="contactFormEmail" class='form-label' >Email</label>
                </p>
                <p>
                  <?php
                    echo $form->render('contactFormEmail',[
                      'class' => 'form-control text-light bg-secondary',
                      'required' => 'required'
                    ]);
                  ?>
                </p>
                <p>
                  <label for="contactFormName" class='form-label'>Имя</label>
                </p>
                <p>
                  <?php
                    echo $form->render('contactFormName',[
                        'class' => 'form-control text-light bg-secondary',
                        'required' => 'required'
                    ]);
                  ?>
                </p>
                <p>
                  <label for="contactFormQuestion" class='form-label'>Вопрос</label>
                </p>
                <p>
                  <?php
                    echo $form->render('contactFormQuestion',[
                        'class' => 'form-control text-light bg-secondary',
                        'required' => 'required',
                        'rows' => 5
                    ]);
                  ?>
                </p>
                <p class='text-center'>
                  <input type='submit' value='Отправить' class='btn btn-primary'/>
                </p>
                <div class="row text-center">
                    <div class="col-lg">
                        <div id='formStatus' class=' invisible spinner-border text-primary mt-2 mb-2' role='status'></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
  </div>
  <h2 class='text-uppercase font-weight-bold mt-3 text-center'>Будем рады Вашим отзывам!</h2>
  <div class='row'>
    <div class='col-lg text-center'>
      <h2><a rel="nofollow" class='text-warning' target='_blank' href='https://go.2gis.com/69t92'>2GIS</a></h2>
      <a rel="nofollow" class='text-light' target='_blank' href='https://go.2gis.com/69t92'>
        <img class='img-fluid' src='/img/qr-2gis.webp' alt='QR-код 2ГИС'>
      </a>
    </div>
    <div class='col-lg text-center'>
      <h2><a rel="nofollow" class='text-warning' target='_blank' href='https://yandex.ru/maps/-/CCUau2C1KD'>Яндекс Карты</a></h2>
      <a rel="nofollow" class='text-light' target='_blank' href='https://yandex.ru/maps/-/CCUau2C1KD'>
        <img class='img-fluid' src='/img/qr-yandex.webp' alt='QR-код Yandex Карты'>
      </a>
    </div>
    <div class='col-lg text-center'>
      <h2><a rel="nofollow" class='text-warning' target='_blank' href='https://goo.gl/maps/QsXebLETe2wfc9rM7'>Google Карты</a></h2>
      <a rel="nofollow" class='text-light' target='_blank' href='https://goo.gl/maps/QsXebLETe2wfc9rM7'>
        <img class='img-fluid' src='/img/qr-google.webp' alt='QR-код Google Maps'>
      </a>
    </div>
  </div>
</div>
