<div id='mainImage'>
  <div class="container" >
    <div class="row align-items-center" id='backgroundIndex'>
      <div class="col-lg">
        <h1 class='mainHeading text-center text-black font-italic font-weight-bold'>ПЛАНЕТА ПУТЕШЕСТВИЙ И РАЗВЛЕЧЕНИЙ</h1>
        <h2 class='mainHeading text-left text-black font-italic font-weight-bold'>СКАЖИ <span class='text-danger'>"ДА"</span></h1>
        <h2 class='mainHeading text-right text-black font-italic font-weight-bold'>НОВЫМ ПРИКЛЮЧЕНИЯМ!</h1>
      </div>
    </div>
  </div>
</div>
<div class="container" id='aboutus'>
  <div class="row">
    <div class="col-lg">
      <h2 class='font-weight-bold text-white text-center text-uppercase mt-3'>О нас</h2>
      <p class='h4 text-white font-italic text-justify'><strong class='text-warning'><u>Планета путешествий и развлечений</u></strong> - туристическая компания, работающая в области индивидуального туризма и корпоративного обслуживания клиентов</p>
      <p class='h5 font-weight-bold text-warning font-italic '>Наши преимущества</p>
      <ul class='h5 text-white font-italic'>
        <li>1 компания для всех туристических услуг</li>
        <li>специализация на индивидуальном обслуживании</li>
        <li>продажа всех видов билетов - в Вашем распоряжении авиа и ж/д кассы</li>
        <li>бронирование туров и жилья</li>
        <li>работа с юридическим лицами</li>
        <li>работа без депозита и посредников</li>
        <li>более <span class='font-weight-bold text-warning'>1000</span> довольных клиентов!</li>
        <li>более <span class='font-weight-bold text-warning'>15</span> лет на рынке туристических услуг - работаем с 2002 года!</li>
      </ul>
      <div class='text-light text-justify'>
        <p>
         Туристическое агентство "Планета путешествий и развлечений" предоставляет сервис для людей, предпочитающих в качестве досуга путешествия.
         Фирма осуществляет продажу различных по направлениям и стоимости туров. У нас Вы можете найти туры выходного дня, горящие туры, туры по России, пакетные туры, экскурсионные туры и многое другое!
        </p>
        <p>
         Зачастую планирование отдыха для большинства людей видится трудным и нудным процессом. Турагентство предоставляет возможность отбросить груз ненужной суеты и начать паковать чемоданы. 
         Все сложности, связанные с перевозками, местами проживания и документами, турфирма берет на себя. 
         А также большим плюсом спланированного туристическим агентством "Планета путешествий и развлечений" тура станет куда более низкая плата за совокупность услуг по сравнению с заказом каждой услуги в отдельности.
        </p>
        <p>
          "Планета путешествий и развлечений" также предлагает подобрать билеты на автобус или поезд и предоставляет любую информацию о расписании рейсов.
          Проблема бронирования и покупки билетов на автобусный и железнодорожные рейсы существует в подавляющем числе городов. 
          На вокзалах к кассам обычно выстроена большая очередь, и невозможно, не потратив время других ожидающих и не торопясь подобрать лучший маршрут, ведь также сотрудники зачастую бывают невежливы, грубы и стараются как можно скорее "избавиться" от занудливого клиента. 
          Именно поэтому стоит воспользоваться предложением организации, оказывающей специализированный сервис по продаже автобусных и железнодорожных билетов.
        </p>
        <p>
          Помимо этого, в офисе туристической фирмы производится продажа билетов на авиарейсы. 
          Здесь есть все существующие предложения, и остается всего лишь определить для себя подходящий по стоимости и дате вылета вариант.
          На данный момент ресурсов по продаже билетов слишком большое количество, и элементарно в них запутаться. Зачастую покупка составляет трудность даже для бывалых туристов. 
          Туристическое агентство "Планета путешествий и развлечений" помогает осуществить выбор за короткое время и без лишних сложностей.  
        </p>
        <h4 class='text-center font-weight-bold font-italic'>
          <u>С нетерпением ждём Вас!</u>
        </h4>
      </div>
    </div>
  </div>
</div>
<div class="container" id='news'>
  <div class="row">
    <div class="col-lg text-white">
      <h2 class='font-weight-bold  text-center text-uppercase mt-3'>Новости</h2>
      <div class="row">
        <div class='container-fluid rounded bg-secondary mb-3 text-justify'>
          <div class='row'>
            <div class='col-lg text-light'>
              <h3 class='font-italic text-warning text-center mb-3'>ПОЕЗДКИ ПО РОССИИ</h3>
              <p>
                25.06 Всероссийский Тургеневский праздник. Большая культурная программа с участием театральных и музыкальных коллективов.
              </p>
              <p>
               03.09.Охотничий фестиваль Записки охотника. Театрализованная  программа раскрывающая традиции дворянской охоты. Выставки  охотничьих собак, охотничья кухня.
              </p>
              <p>
               03.10 Константиново Рязанская обл. День Рождения Есенина. Выступление поэтов, артистов.
              </p>
              <P>
                Стоимость в экскурсии в Спасско-Лутовиново  3000 р. на человека. Входит проезд на 19 местном комфортабельном автобусе, входные билеты. Группа 12 человек. В Константиново стоимость 4000 р.+ одна ночь в гостинице Константиново или рядом (цена уточняется).
              </P>
              <p>Для бронирования обращайтесь к нам!</p>
              <p class='text-left smallFont'>Источники изображений: http://spasskoye-lutovinovo.ru/ii-ohotnichij-festival-zapiski-ohotnika/</p>
            </div>
          </div>
          <div class='row text-center'>
            <div class='col-lg'><img alt='Охотничий фестиваль «Записки охотника»' src='img/hunting-festival1.webp' srcset='img/hunting-festival1-360.webp 360w, img/hunting-festival1-480.webp 480w, img/hunting-festival1-720.webp 720w, img/hunting-festival1-1080.webp 1080w, img/hunting-festival1-1440.webp 1440w, img/hunting-festival1-1600.webp 1600w, img/hunting-festival1-1920.webp 1920w, img/hunting-festival1-2048.webp 2048w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
            <div class='col-lg'><img alt='Охотничий фестиваль «Записки охотника»' src='img/hunting-festival2.webp' srcset='img/hunting-festival2-360.webp 360w, img/hunting-festival2-480.webp 480w, img/hunting-festival2-720.webp 720w, img/hunting-festival2-1080.webp 1080w, img/hunting-festival2-1440.webp 1440w, img/hunting-festival2-1600.webp 1600w, img/hunting-festival2-1920.webp 1920w, img/hunting-festival2-2048.webp 2048w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
          </div>
          <div class='row text-center'>
            <div class='col-lg'><img alt='Охотничий фестиваль «Записки охотника»' src='img/hunting-festival3.webp' srcset='img/hunting-festival3-360.webp 360w, img/hunting-festival3-480.webp 480w, img/hunting-festival3-720.webp 720w, img/hunting-festival3-1080.webp 1080w, img/hunting-festival3-1440.webp 1440w, img/hunting-festival3-1600.webp 1600w, img/hunting-festival3-1920.webp 1920w, img/hunting-festival3-2048.webp 2048w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
            <div class='col-lg'><img alt='Охотничий фестиваль «Записки охотника»' src='img/hunting-festival4.webp' srcset='img/hunting-festival4-360.webp 360w, img/hunting-festival4-480.webp 480w, img/hunting-festival4-720.webp 720w, img/hunting-festival4-1080.webp 1080w, img/hunting-festival4-1440.webp 1440w, img/hunting-festival4-1600.webp 1600w, img/hunting-festival4-1920.webp 1920w, img/hunting-festival4-2048.webp 2048w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
            <div class='col-lg'><img alt='Охотничий фестиваль «Записки охотника»' src='img/hunting-festival5.webp' srcset='img/hunting-festival5-360.webp 360w, img/hunting-festival5-480.webp 480w, img/hunting-festival5-720.webp 720w, img/hunting-festival5-1080.webp 1080w, img/hunting-festival5-1440.webp 1440w, img/hunting-festival5-1600.webp 1600w, img/hunting-festival5-1920.webp 1920w, img/hunting-festival5-2048.webp 2048w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
          </div>
        </div>
        <div class='container-fluid rounded bg-secondary mb-3 text-justify'>
          <div class='row'>
            <div class='col-lg text-light'>
                <h3 class='font-italic text-warning text-center text-uppercase mb-3'>отдыхаем на чёрном море: отели с системой "всё включено"</h3>
                <p> Уже мечтаете о летнем отпуске на морском побережье? Мы в турагентстве «<a class='text-white' href='/'>Планета путешествий и развлечений</a>» предлагаем выбрать подходящее направление для отдыха на российских курортах.</p>
                <p>Рассказываем об отелях с системой «всё включено», в которых можно остановиться в июне:</p>
                <ul>
                  <li>в Крыму</li>
                  <li class='noList'>
                    <ul>
                      <li>отель «Ателика Горизонт» в Алуште (2 звезды) – от 39 900 ₽</li>
                      <li>отель «Ателика Горизонт» в Алуште (2 звезды) – от 39 900 ₽</li>
                      <li>отель «Ателика Горизонт» в Алуште (2 звезды) – от 39 900 ₽</li>
                    </ul>
                  </li>
                  <li>в Анапе</li>
                  <li class='noList'>
                    <ul>
                      <li>отель «Ателика Гранд Меридиан» (3 звезды) – от 41 000 ₽</li>
                      <li>отель Democratia Ultra All Inclusive (3 звезды) – от 64 000 ₽</li>
                      <li>отель Fioleto All Inclusive Family Resort (4 звезды) – от 91 700 ₽</li>
                      <li>отель MoreLeto Ultra All Inclusive (4 звезды) – от 95 200 ₽</li>
                    </ul>
                  </li>
                  <li>в Сочи/Адлере</li>
                  <li class='noList'>
                    <ul>
                      <li>отель Bridge Resort (4 звезды) – от 128 000 ₽</li>
                      <li>отель Alean Family Sputnik (4 звезды) – от 151 500 ₽</li>
                      <li>отель «Прометей Клуб» в Лазаревском (4 звезды) – от 72 000 ₽</li>
                      <li>пансионат «Бургас» в п. Кудепста (3 звезды) – от 50 400 ₽</li>
                    </ul>
                  </li>
                  <li>в Геленджике</li>
                  <li class='noList'>
                    <ul>
                      <li>отель Alean Family Resort & Spa Biarritz (4 звезды) – от 128 500 ₽</li>
                    </ul>
                  </li>
                </ul>
                <p>Обратите внимание: в указанную стоимость входят проживание и питание по системе «всё включено» на 7 ночей для двух взрослых. Дорога оплачивается отдельно.</p>
                <p>Запланируйте летний отпуск вместе с нами!</p>
                <div class='singleImg text-center'><img alt='Отдых на Чёрном море»' src='img/crimea-1080.webp' srcset='img/crimea-360.webp 360w, img/crimea-480.webp 480w, img/crimea-720.webp 720w, img/crimea-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
            </div>
          </div>
        </div>
        <div class='container-fluid rounded bg-secondary mb-3 text-justify'>
          <div class='row'>
            <div class='col-lg text-light'>
                <h3 class='font-italic text-warning text-center text-uppercase mb-3'>8 идей, что посмотреть на кубе</h3>
                <p>🇨🇺 Роскошные пляжи, богатая история, необычная культура – всё это про Кубу, гостеприимный Остров свободы. Отдых здесь станет настоящим приключением с танцами, коктейлями и вкусной едой.</p>
                <p>Сегодня рассказываем, чем заняться во время отпуска на Кубе:</p>
                <p>1) Провести один день как Эрнест Хемингуэй.<br>Посетите двухэтажный дом-музей американского классика с 22 тысячами экспонатов и аутентичной атмосферой. Здесь писатель создал роман «По ком звонит колокол» и повесть «Старик и море».</p>
                <p>2) Повеселиться в кабаре «Тропикано».<br>Вас ждёт настоящее красочное шоу от привлекательных танцовщиц, полное песен, ярких нарядов и куража. Здесь выступают акробаты, звучат джазовые композиции, а официанты подают шедевры кубинских поваров и местный ром.</p>
                <p>3) Прогуляться по колониальному городу-музею.<br>Тринидад основали в 16 веке испанские конкистадоры – мощёные улицы этого города полны истории. Вы увидите старые церкви, дворцы и дома в колониальном стиле с черепичными крышами.</p>
                <p>4) Подружиться с крокодилами.<br>Уникальная экосистема природного парка «Съенага-де-Сапата» признана заболоченной территорией международного значения. Здесь можно наблюдать за редкими птицами, ламантинами и, конечно, кубинскими крокодилами.</p>
                <p>5) Почтить память Че Гевары.<br>Мемориальный комплекс Эрнесто Че Гевары хранит личные вещи революционера, документы и письма. На гранитном постаменте в центре площади возвышается бронзовый монумент и увековечен девиз – «Всегда до победы!».</p>
                <p>6) Почувствовать себя защитником от пиратских набегов.<br>Ла-Реаль-Фуэрса – одна из самых старых крепостей Гаваны. Сейчас здесь открыт Морской музей, в котором есть четырёхметровая копия судна «Сантизма Тринидад», самого большого корабля 18 века.</p>
                <p>7) Оценить архитектуру Капитолия.<br>Кубинский парламент заседал в этом масштабном и красивом здании всего 30 лет – сейчас здесь размещается конгресс-центр, а всех желающих пускают внутрь.</p>
                <p>8) Встретить закат на набережной Малекон.<br>Культовое место, собирающее гостей Гаваны, простирается на 8 км вдоль побережья. Здесь проходят фестивали и карнавалы, выступают ансамбли и гуляют местные и туристы.</p>
                <p>Для бронирования путешествия на Кубу обращайтесь к нам!</p>
                <p class='text-left smallFont'>Источники изображений: https://www.islands.com/7-things-to-know-before-you-book-cruise-to-cuba/, https://theculturetrip.com/caribbean/cuba/articles/13-must-visit-attractions-in-cuba/, https://irshadgul.com/11-the-meaning-of-crocodile-dreams-according-to-psychology-describe-feelings/, https://holiplus.com/en/tour/522oM/ride-to-santa-clara-in-old-fashion-american-classic-cars-tour, https://en.wikipedia.org/wiki/Castillo_de_la_Real_Fuerza</p>
            </div>
          </div>
          <div class='row text-center'>
            <div class='col-lg'><img alt='Отпуск на Кубе' src='img/cuba-ideas-1080.webp' srcset='img/cuba-ideas-360.webp 360w, img/cuba-ideas-480.webp 480w, img/cuba-ideas-720.webp 720w, img/cuba-ideas-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
            <div class='col-lg'><img alt='Дом-музей американского классика Эрнест Хемингуэйя' src='img/cuba-ernest-hemingway-1080.webp' srcset='img/cuba-ernest-hemingway-360.webp 360w, img/cuba-ernest-hemingway-480.webp 480w, img/cuba-ernest-hemingway-720.webp 720w, img/cuba-ernest-hemingway-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
            <div class='col-lg'><img alt='Кабаре «Тропикано»' src='img/cuba-tropicana-1080.webp' srcset='img/cuba-tropicana-360.webp 360w, img/cuba-tropicana-480.webp 480w, img/cuba-tropicana-720.webp 720w, img/cuba-tropicana-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
          </div>
          <div class='row text-center'>
            <div class='col-lg'><img alt='Колониальный город-музей Тринидад' src='img/cuba-trinidad-1080.webp' srcset='img/cuba-trinidad-360.webp 360w, img/cuba-trinidad-480.webp 480w, img/cuba-trinidad-720.webp 720w, img/cuba-trinidad-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
            <div class='col-lg'><img alt='Кубинские крокодилы' src='img/cuba-crocodiles-1080.webp' srcset='img/cuba-crocodiles-360.webp 360w, img/cuba-crocodiles-480.webp 480w, img/cuba-crocodiles-720.webp 720w, img/cuba-crocodiles-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
            <div class='col-lg'><img alt='Че Гевара' src='img/cuba-che-guevara-1080.webp' srcset='img/cuba-che-guevara-360.webp 360w, img/cuba-che-guevara-480.webp 480w, img/cuba-che-guevara-720.webp 720w, img/cuba-che-guevara-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
          </div>
          <div class='row text-center'>
            <div class='col-lg'><img alt='Ла-Реаль-Фуэрса' src='img/cuba-fortress-1080.webp' srcset='img/cuba-fortress-360.webp 360w, img/cuba-fortress-480.webp 480w, img/cuba-fortress-720.webp 720w, img/cuba-fortress-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
            <div class='col-lg'><img alt='Капитолий на Кубе' src='img/cuba-capitol-1080.webp' srcset='img/cuba-capitol-360.webp 360w, img/cuba-capitol-480.webp 480w, img/cuba-capitol-720.webp 720w, img/cuba-capitol-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
            <div class='col-lg'><img alt='Набережная Малекон' src='img/cuba-malekon-1080.webp' srcset='img/cuba-malekon-360.webp 360w, img/cuba-malekon-480.webp 480w, img/cuba-malekon-720.webp 720w, img/cuba-malekon-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
          </div>
        </div>
        <div class='container-fluid rounded bg-secondary mb-3 text-justify'>
          <div class='row'>
            <div class='col-lg text-light'>
                <h3 class='font-italic text-warning text-center text-uppercase mb-3'>5 отелей для отдыха в красной поляне</h3>
                <p>🏔Горнолыжный сезон в разгаре, и провести его в Красной Поляне – отличная идея. Тем более из Белгорода есть прямые вылеты в Сочи по средам, четвергам и воскресеньям.</p>
                <p>Мы сделали подборку отелей, в которых вы можете остановиться, если отправитесь отдыхать в феврале:</p>
                <ol>
                  <li>Комплекс отдыха «Беларусь» (4 звезды)</li>
                  <li class='noList'>
                    <ul>
                      <li>из окон открывается вид на горы, можно взять инвентарь в прокат, а также искупаться в крытом бассейне с подогревом</li>
                      <li>от 30 500 ₽ за четыре ночи для двух взрослых</li>
                    </ul>
                  </li>
                  <li>Гранд отель «Поляна» (5 звёзд)</li>
                  <li class='noList'>
                    <ul>
                      <li>к услугам гостей крытый и открытый бассейны, оздоровительный центр, четыре ресторана и номера с живописными видами</li>
                      <li>от 65 600 ₽ за четыре ночи для двух взрослых</li>
                    </ul>
                  </li>
                  <li>Апарт-отель «Снега» (4 звезды)</li>
                  <li class='noList'>
                    <ul>
                      <li>удобное расположение рядом с главными горнолыжными курортами, спа-комплекс и роскошные номера</li>
                      <li>от 54 400 ₽ за четыре ночи для двух взрослых</li>
                    </ul>
                  </li>
                  <li>Отель «Аркадия» (4 звезды)</li>
                  <li class='noList'>
                    <ul>
                      <li>в отеле есть станция проката необходимого инвентаря, тренажёрный зал и турецкий хаммам</li>
                      <li>от 53 000 ₽ за четыре ночи для двух взрослых</li>
                    </ul>
                  </li>
                  <li>Апартаменты «Горки Город» (3 звезды)</li>
                  <li class='noList'>
                    <ul>
                      <li>удобные апартаменты в современном стиле с видом на живописное предгорье Кавказа</li>
                      <li>от 65 900 ₽ за четыре ночи для двух взрослых</li>
                  </ul>
                  </li>
                </ol>
                <p>Обращайтесь в наше агентство – мы подберём для вас подходящий отель!</p>
                <p class='text-left smallFont'>Источники изображений: https://www.pinterest.ch/pin/556687203942588424/, https://sanatorium-booking.com/sanatorium/krasnodarskiy-kray/belarus_krasnaya_polyana, https://lux-trip.ru/luchshie-oteli-krasnoy-polyanyi-sochi-v-gorah-dlya-otdyiha-zimoy-na-gornolyizhnyih-kurortah-vip-oteli-lyuks/, https://www.booking.com/hotel/ru/gorky-gorod-apartments.html?activeTab=photosGallery</p>
                <div class='row text-center'>
                  <div class='col-lg'><img alt='Отдых в Красной Поляне' src='img/krasnaya-polyana-hotels-1080.webp' srcset='img/krasnaya-polyana-hotels-360.webp 360w, img/krasnaya-polyana-hotels-480.webp 480w, img/krasnaya-polyana-hotels-720.webp 720w, img/krasnaya-polyana-hotels-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                  <div class='col-lg'><img alt='Комплекс отдыха Беларусь' src='img/hotel-belorus-1080.webp' srcset='img/hotel-belorus-360.webp 360w, img/hotel-belorus-480.webp 480w, img/hotel-belorus-720.webp 720w, img/hotel-belorus-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                  <div class='col-lg'><img alt='Гранд отель Поляна' src='img/hotel-polyana-1080.webp' srcset='img/hotel-polyana-360.webp 360w, img/hotel-polyana-480.webp 480w, img/hotel-polyana-720.webp 720w, img/hotel-polyana-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                </div>
                <div class='row text-center'>
                  <div class='col-lg'><img alt='Апарт-отель Снега' src='img/hotel-snows-1080.webp' srcset='img/hotel-snows-360.webp 360w, img/hotel-snows-480.webp 480w, img/hotel-snows-720.webp 720w, img/hotel-snows-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                  <div class='col-lg'><img alt='Отель Аркадия' src='img/hotel-arcadia-1080.webp' srcset='img/hotel-arcadia-360.webp 360w, img/hotel-arcadia-480.webp 480w, img/hotel-arcadia-720.webp 720w, img/hotel-arcadia-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                  <div class='col-lg'><img alt='Апартаменты Гооки Город' src='img/apartments-gorki-gorod-1080.webp' srcset='img/apartments-gorki-gorod-360.webp 360w, img/apartments-gorki-gorod-480.webp 480w, img/apartments-gorki-gorod-720.webp 720w, img/apartments-gorki-gorod-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                </div>
            </div>
          </div>
        </div>
        <div class='container-fluid rounded bg-secondary mb-3 text-justify'>
          <div class='row'>
            <div class='col-lg text-light'>
                <h3 class='font-italic text-warning text-center text-uppercase mb-3'>северное сияние и встреча с океаном: летим в мурманск</h3>
                <p>💫 Подобрали тур для настоящих любителей приключений – путешествие за Полярный круг.</p>
                <p>Что вас ждёт в самом северном уголке России?</p>
                <ul style="list-style-type:none">
                  <li>🧊 охота за северным сиянием</li>
                  <li>🧊 экскурсия по Мурманску – самому крупному заполярному городу в мире</li>
                  <li>🧊 поездка на край земли – в Териберку, где снимался нашумевший фильм «Левиафан»</li>
                  <li>🧊 посещение удивительного кладбища кораблей</li>
                  <li>🧊 незабываемая встреча с Северным Ледовитым океаном</li>
                  <li>🧊 знакомство с обычаями и традициями кольских саамов</li>
                </ul>
                <p>Даты тура: 18–20 февраля.</p>
                <p>Стоимость – от 32 900 ₽.</p>
                <p>Что входит в 3-дневный тур?</p>
                <ul>
                  <li>проживание в гостинице выбранной категории</li>
                  <li>2 завтрака и 3 обеда</li>
                  <li>комфортное передвижение на автобусе</li>
                  <li>экскурсии и услуги гида</li>
                  <li>трансфер</li>
                </ul>
                <p>Обратите внимание: авиабилет до Мурманска и обратно оплачивается отдельно.</p>
                <p>Уже хотите оказаться за Полярным кругом? Для брони тура звоните в наше туристическое агентство!</p>
                <p class='text-left smallFont'>Источники изображений: https://sciencing.com/tundra-climate-6389826.html</p>
                <div class='row text-center'>
                  <div class='col-lg'><img alt='Путешествие в Мурманск' src='img/murmansk-1080.webp' srcset='img/murmansk-360.webp 360w, img/murmansk-480.webp 480w, img/murmansk-720.webp 720w, img/murmansk-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                  <div class='col-lg'><img alt='Мурманские корабли' src='img/murmansk-ship-1080.webp' srcset='img/murmansk-ship-360.webp 360w, img/murmansk-ship-480.webp 480w, img/murmansk-ship-720.webp 720w, img/murmansk-ship-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                  <div class='col-lg'><img alt='Териберка' src='img/teriberka-1080.webp' srcset='img/teriberka-360.webp 360w, img/teriberka-480.webp 480w, img/teriberka-720.webp 720w, img/teriberka-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                </div>
                <div class='row text-center'>
                  <div class='col-lg'><img alt='Северное сияние в Териберке' src='img/teriberka-night-1080.webp' srcset='img/teriberka-night-360.webp 360w, img/teriberka-night-480.webp 480w, img/teriberka-night-720.webp 720w, img/teriberka-night-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                  <div class='col-lg'><img alt='Кладбище кораблей' src='img/teriberka-ship-cemetery-1080.webp' srcset='img/teriberka-ship-cemetery-360.webp 360w, img/teriberka-ship-cemetery-480.webp 480w, img/teriberka-ship-cemetery-720.webp 720w, img/teriberka-ship-cemetery-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                  <div class='col-lg'><img alt='Саамская деревня' src='img/sami-village-1080.webp' srcset='img/sami-village-360.webp 360w, img/sami-village-480.webp 480w, img/sami-village-720.webp 720w, img/sami-village-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                  <div class='col-lg'><img alt='Саамская деревня' src='img/sami-village2-1080.webp' srcset='img/sami-village2-360.webp 360w, img/sami-village2-480.webp 480w, img/sami-village2-720.webp 720w, img/sami-village2-1080.webp 1080w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px" class='img-fluid mb-3'></div>
                </div>
            </div>
          </div>
        </div>
        <div class='container-fluid mb-3 text-center'>
          <div class='row'>
            <div class='col-lg'>
              <a class='text-white' href='/news'>Все новости -></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
