<div class="container">
  <div class="row">
    <div class="col text-white text-justify">
      <h1 id='news' class='font-weight-bold  text-center text-uppercase mt-3'>горящие путёвки и туры</h1>
      <p><a class='text-white' href='/'>"Планета путешествий и развлечений"</a> предлагает Вашему вниманию огромное количество туров по популярным и разнообразным направлениям.</p>
      <p>Для получения более подробной информации <a class='text-white font-italic' href='/contacts'>обращайтесь</a> в наше туристическое агентство или <a class='text-white font-italic' href='/contacts#supporForm'>воспользуйтесь формой обратной связи!</a></p>
      <ul class="nav nav-pills mb-3" id="tours-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="pills-tours-russia-tab" data-toggle="pill" href="#pills-tours-russia" role="tab" aria-controls="pills-tours-russia" aria-selected="true">Туры по России</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link" id="pills-tours-abroad-tab" data-toggle="pill" href="#pills-tours-abroad" role="tab" aria-controls="pills-tours-abroad" aria-selected="false">Заграничные туры</a>
        </li>
      </ul>
      <div class="tab-content" id="pills-tabContent-tours">
        <div class="tab-pane fade show active" id="pills-tours-russia" role="tabpanel" aria-labelledby="pills-tours-russia-tab">
          <div class='container text-body'>
            <div class='row row-cols-lg-3 row-cols-md-2 row-cols-sm-1'>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Туры по России - Калининград' src='img/russian-tours-kaliningrad-720.webp' srcset='img/russian-tours-kaliningrad-360.webp 360w, img/russian-tours-kaliningrad-480.webp 480w, img/russian-tours-kaliningrad-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Калининград</h5>
                    <p class="card-text">🧡 Край янтаря, жемчужина Балтики, маленькая Европа – у Калининграда много названий. Мы в турагентстве предлагаем убедиться, что он – это всё и даже больше.</p>
                    <p>✈ Из Белгорода летают прямые рейсы до Калининграда – это первая хорошая новость. Вторая: мы подберём подходящий тур под любые удобные для вас даты.</p>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Туры по России - Домбай' src='img/russian-tours-dombay-720.webp' srcset='img/russian-tours-dombay-360.webp 360w, img/russian-tours-dombay-480.webp 480w, img/russian-tours-dombay-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Домбай</h5>
                    <p class="card-text">Подберём для вас в агентстве тур в зимний Домбай. Туда едут за:</p>
                    <p>Зимой это популярный горнолыжный курорт – и отличный вариант для праздничного отпуска.</p>
                    <p>Прямые рейсы из Белгорода в Минеральные Воды – по средам и субботам.</p>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Туры по России - Домбай' src='img/russian-tours-krasnaya-polyana-720.webp' srcset='img/russian-tours-krasnaya-polyana-360.webp 360w, img/russian-tours-krasnaya-polyana-480.webp 480w, img/russian-tours-krasnaya-polyana-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Красная Поляна</h5>
                    <p class="card-text"> Чтобы заказать тур, обращайтесь в турагентство «Планета путешествий и развлечений»!</p>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Туры по России - Минеральные Воды' src='img/russian-tours-mineralnye-vody-720.webp' srcset='img/russian-tours-mineralnye-vody-360.webp 360w, img/russian-tours-mineralnye-vody-480.webp 480w, img/russian-tours-mineralnye-vody-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Минеральные Воды</h5>
                    <p> По средам и субботам из Белгорода отправляются прямые рейсы в Минеральные Воды. Оттуда вы сможете попасть в любой из курортов Ставропольского края и отдохнуть с пользой для здоровья.</p>
                    <p>Вам достаточно лишь выбрать подходящий санаторий – предлагаем несколько вариантов для разных бюджетов.</p>
                    <p>🚌 Кроме того, вы сможете съездить на увлекательные экскурсии – увидеть незабываемое плато Бермамыт или посетить город Грозный. Мы обязательно поможем вам подобрать самое интересное направление.</p>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Туры по России - Казань' src='img/russian-tours-kazan-720.webp' srcset='img/russian-tours-kazan-360.webp 360w, img/russian-tours-kazan-480.webp 480w, img/russian-tours-kazan-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Прямым рейсом в Казань</h5>
                    <p>До 31 декабря в Казань из Белгорода рейсы летают по понедельника и пятницам – самое время планировать путешествие.</p>
                    <p>Выходные в Казани станут самым ярким событием этого декабря.</p>
                    <p>Тур составляется индивидуально под ваши предпочтения.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="pills-tours-abroad" role="tabpanel" aria-labelledby="pills-tours-abroad-tab">
          <div class='container text-body'>
            <div class='row row-cols-lg-3 row-cols-md-2 row-cols-sm-1'>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Заграничные туры - Турция' src='img/tours-abroad-turkey-720.webp' srcset='img/tours-abroad-turkey-360.webp 360w, img/tours-abroad-turkey-480.webp 480w, img/tours-abroad-turkey-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Турция</h5>
                    <p>Отели на любой вкус, русскоговорящий персонал. Увлекательные экскурсии, которые познакомят с богатой историей и уникальным историческим наследием страны.</p>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Заграничные туры - Пхукет' src='img/tours-abroad-phuket-720.webp' srcset='img/tours-abroad-phuket-360.webp 360w, img/tours-abroad-phuket-480.webp 480w, img/tours-abroad-phuket-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Пхукет</h5>
                    <p>Идеальный вариант для побега в лето посреди зимы: ласковое солнце, тёплое и спокойное море, много свежих фруктов. Ничто не помешает загорать, ловить дзен на пляже и выбираться на экскурсии. </p>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Заграничные туры - Венесуэла' src='img/tours-abroad-venezuela-720.webp' srcset='img/tours-abroad-venezuela-360.webp 360w, img/tours-abroad-venezuela-480.webp 480w, img/tours-abroad-venezuela-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Венесуэла</h5>
                    <p>Здесь есть всё для запоминающегося отпуска: километры пляжей, величественные Анды, самый высокий в мире водопад и удивительные растения и животные (что думаете насчёт знакомства с анакондой?). </p>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Заграничные туры - Дубай' src='img/tours-abroad-dubai-720.webp' srcset='img/tours-abroad-dubai-360.webp 360w, img/tours-abroad-dubai-480.webp 480w, img/tours-abroad-dubai-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Дубай</h5>
                    <p>Пусть море и не такое тёплое, зато небоскрёбы и фонтаны поражают воображение, как и уровень сервиса. В январе здесь стартует Торговый фестиваль – настоящий рай для шопоголиков. </p>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Заграничные туры - Куба' src='img/tours-abroad-cuba-720.webp' srcset='img/tours-abroad-cuba-360.webp 360w, img/tours-abroad-cuba-480.webp 480w, img/tours-abroad-cuba-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Куба</h5>
                    <p>Пляжный сезон в разгаре! Каждый день на Кубе – это праздник, полный карибского колорита, отличного алкоголя и духа свободы. </p>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Заграничные туры - Азербайджан' src='img/tours-abroad-azerbaijan-720.webp' srcset='img/tours-abroad-azerbaijan-360.webp 360w, img/tours-abroad-azerbaijan-480.webp 480w, img/tours-abroad-azerbaijan-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Азербайджан</h5>
                    <p>Азербайджан. Горнолыжные туры:</p>
                    <ul>
                      <li>Шахдаг</li>
                      <li>Туфандаг</li>
                      <li>Агбулаг + Баку</li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Заграничные туры - Египет' src='img/tours-abroad-egypt-720.webp' srcset='img/tours-abroad-egypt-360.webp 360w, img/tours-abroad-egypt-480.webp 480w, img/tours-abroad-egypt-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Египет</h5>
                    <p>Даже зимой здесь солнечно, а воздух прогревается до +25 °C. Если давно хотели попробовать сёрфинг или дайвинг, Красное море уже ждёт вас. Да и экскурсии по популярным достопримечательностям никто не отменял. </p>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Заграничные туры - Баку' src='img/tours-abroad-baku-720.webp' srcset='img/tours-abroad-baku-360.webp 360w, img/tours-abroad-baku-480.webp 480w, img/tours-abroad-baku-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Баку</h5>
                    <p>Отправляемся в солнечный Баку – столицу Азербайджана. Город будет одинаково интересен и любителям истории, и ценителям современной архитектуры, и поклонникам шоппинга и вкусной еды.</p>
                  </div>
                </div>
              </div>
              <div class='col mb-3'>
                <div class="card h-100">
                  <img alt='Заграничные туры - Стамбул' src='img/tours-abroad-instanbul-720.webp' srcset='img/tours-abroad-instanbul-360.webp 360w, img/tours-abroad-instanbul-480.webp 480w, img/tours-abroad-instanbul-720.webp 720w' sizes="(max-width: 360px) 285px, (max-width: 480px) 380px, (max-width: 720px) 575px, (max-width: 1080px) 860px, (max-width: 1440px) 1150px, (max-width: 1600px) 1280px, (max-width: 1920px) 1535px, (max-width: 2048px) 2048px, 2049px">
                  <div class="card-body">
                    <h5 class="card-title">Стамбул</h5>
                    <p>Тур в разноцветный и колоритный Стамбул. Даже в январе столбик термометра здесь не опускается ниже нуля, так что можно смело гулять и исследовать город.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>