<div class="container">
  <div class="row">
    <div class="col-lg text-light">
      <form id='addFaqForm' action="/admin/addFaq" method='post'>
        <div class="row">
          <div class="col-lg text-center">
            <label for="faqFormHeader">Заголовок</label>
            <input type='text' required id='faqFormHeader' name='faqFormHeader' class="form-control bg-secondary text-light">
            <label for="faqFormAnswer">Ответ</label>
            <textarea required class="form-control bg-secondary text-light" id='faqFormAnswer' name="faqFormAnswer" rows="8"></textarea>
            <label for="faqFormHidden">Скрытый</label>
            <input class='mt-3 bg-secondary text-light' type="checkbox" name='faqFormHidden' id='faqFormHidden'><br>
          </div>
          <div class="container-fluid text-center">
            <div class="row">
              <div class="col-lg">
                <button type="submit" class="btn btn-primary mt-2 text-center">Добавить</button>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg table-responsive">
      <table class="table text-center text-light mt-3 border">
        <thead>
          <tr>
            <th>Название</th>
            <th>Позиция</th>
            <th>Скрытый</th>
            <th>Действия</th>
          </tr>
        </thead>
        <tbody>
          <?php
            foreach($faqs as $faq) {
              echo "<tr>";
              echo "<td>".$faq->faq_title."</td>";
              $id = $faq->faq_id;
              echo "<td>".$faq->faq_position."</td>";
              if($faq->faq_hidden == 0) {
                echo "<td><input type='checkbox' disabled></td>";
              } else {
                echo "<td><input type='checkbox' checked disabled></td>";
              }
              echo "<td><button class='btn btn btn-danger removeFaqBtn' id='removeFaqBtn$id'>Удалить</button>
                <button class='btn btn btn-warning editFaqBtn' id='editFaqBtn$id' data-toggle='modal' data-target='#staticEditFaqModal'>Редактировать</button></td>";
              echo '</tr>';
            }
          ?>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="modal fade" id="staticEditFaqModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticModalFaqEditForm" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Редактировать</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form id='editFaqForm' action="/admin/editFaq" method='post'>
        <div class="modal-body" id='staticModalFaqEditForm'>
          <div class="row">
            <div class="col-lg text-center">
              <label>#</label>
              <p id='editFaqFormId'></p>
            </div>
            <div class="col-lg text-center">
              <label for="editFaqFormHeader">Заголовок</label>
              <input type='text' required id='editFaqFormHeader' name='editFaqFormHeader' class="form-control">
            </div>
          </div>
          <div class="row text-center">
            <div class="col-lg">
              <label for="editFaqFormHidden">Скрытый</label><br>
              <input type="checkbox" name='editFaqFormHidden' id='editFaqFormHidden'>
            </div>
            <div class="col-lg">
              <label for="editFaqFormPosition">Позиция</label>
              <select class="form-control" name='editFaqFormPosition' id="editFaqFormPosition">
              </select>
            </div>
          </div>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
        <button type="submit" class="btn btn-primary">Сохранить</button>
      </div>
    </form>
    </div>
  </div>
</div>
